export const appConfig = {
  name: 'Create Next App',
  url: 'http://localhost:3000',
  ogImage: '/og.jpg',
  description: 'Generated by create next app',
  authors: [{ name: 'Progamo LTDA', url: 'https://www.progamo.com.br' }],
  creator: 'Manoel Neto',
  links: {
    github: 'https://github.com/ManoelDev',
  },
};

export type appConfig = typeof appConfig;
